### ISSUE TITLE
paper issue

### ISSUE THREAD

**Issue by qdd1234** [SeanChenxy/HandMesh#1]
Hi
Thans for your wonderful work. I have some questions referring to 2D hand pose estimtion followed:
1.You train your model on a 3D benchmark,But Your model can still estimation 2D estimation,How do your model achieve?
2.Dose model can train on a 2D benchmark directly?

Thanks

**Comment by SeanChenxy** [comment]
Hi, 
Please refer to Figure 2. 
1. In "2D cue extraction", We use the hourglass network to predict 2D information, and training data contains 2D annotations. 
2. If you try this repo on a 2D benchmark, you would like to remove "3D mesh recovery" and corresponding loss fuctions.

**Comment by qdd1234** [comment]
Could you share the code about RHD dateset?

**Comment by SeanChenxy** [comment]
It could come after the conference. You now can refer to https://github.com/lixiny/bihand?utm_source=catalyzex.com
