### ISSUE TITLE
How to generate 'ano' data in FreiHAND evaluation dataset?

### ISSUE THREAD

**Issue by tlok666** [SeanChenxy/HandMesh#12]
![image](https://user-images.githubusercontent.com/12291907/129685161-eb7b1c26-3048-47d1-b201-3358619e8c07.png)
Hi, SeanChenxy,

The FreiHAND dataset has no annotation in the evaluation dataset. How to collect the ano folder shown in the above figure? Thanks.

**Comment by SeanChenxy** [comment]
Hi, I am sorry for this mistake. FreiHAND evaluation do not need 'anno'. I have updated the README.
