### ISSUE TITLE
About the re-implemented model of YoutubeHand 

### ISSUE THREAD

**Issue by EAST-J** [SeanChenxy/HandMesh#14]
Hi Xingyu, Thanks for your great work. I see in the Experiment part of the paper, you use YouTubeHand as the baseline. I wonder would you release this part of code and model?

**Comment by SeanChenxy** [comment]
Hi, I have re-implement YoutubeHand (https://github.com/SeanChenxy/HandMesh/blob/main/cmr/ytbhand.py). But I have not re-train it. You could use it according to your needs.

**Comment by yuyu19970716** [comment]
Hello, I can't find the ytbhand.py file in the code, can you provide it?

**Comment by EAST-J** [comment]
> Hello, I can't find the ytbhand.py file in the code, can you provide it?

You can find in cmr/models/ytbhand.py

**Comment by yuyu19970716** [comment]
Oh I found it! Thank you so much, this question is so sloppy!

**Comment by yuyu19970716** [comment]
Hello, I have another question to ask. This question may also be rather silly. I want to correspond the model code of DenseStack_Backnone with the paper, but I feel that I am looking at it in a mess. May I ask where the 2d encoder-decoder architecture and cascade are reflected in the model? At the same time, is the final generated latent Fe? Is uv-reg Lp? So sorry,I'm new to this direction.
Looking forward to your reply! Thanks in advance!
