### ISSUE TITLE
smplpytorch等问题

### ISSUE THREAD

**Issue by Whiskysu** [SeanChenxy/HandMesh#15]
你好，陈先生，您的这个手部Mesh重建的工作我觉得非常棒。但是代码似乎存在一些问题：
第一，您在readme.md文件的预训练模型位置似乎写错了一个。
![image](https://user-images.githubusercontent.com/46953515/146389862-86beb2f3-23eb-4760-9fe1-443ba39c7587.png)
根据你提供的gooledrive预训练模型下载文件应该是这样的。
![image](https://user-images.githubusercontent.com/46953515/146390136-9c2922a0-6f35-4c43-ae34-786adfb03eca.png)

第二，我按照你的readme.md步骤，运行./scripts/demo_cmr.sh，会提示smplpytorch无法找到，原因在smplpytorch这个文件应当在HandMesh主文件下，而不是smplpytorch文件下的smplpytorch。下图是我修改后的文件夹形式。
![image](https://user-images.githubusercontent.com/46953515/146382173-2928cb3e-bb75-4608-a493-7c54bc4b24be.png)
第三，我修改上述文件后，FreiHAND数据集正确放置，但是运行训练代码时：
./scripts/eval_cmr_freihand.sh
出现一下报错：
![image](https://user-images.githubusercontent.com/46953515/146383692-e49cb8a6-e747-4b37-a9dc-215a80499d62.png)
因此我将/home/su/文档/HandMesh/datasets/FreiHAND/freihand.py", line 125加了contours = list(contours)，将contours改为了list类型，再排完顺序后又转为tuple类型，如下图所示，
![image](https://user-images.githubusercontent.com/46953515/146389349-24b227a4-6494-4e50-bc55-e46b27950f9d.png)
然后我修改了fh_utils文件打印了idx，确实有列表存在，这是一种错误，还有一种报错freihand路径没有rgb2文件夹，不知道是不是漏了啥没写；
![image](https://user-images.githubusercontent.com/46953515/146388963-8bbb66b6-369e-4c55-8fae-ae2e9204ba14.png)
![image](https://user-images.githubusercontent.com/46953515/146388716-44d9d534-c86e-47c4-8231-bc5ed8eec7a8.png)

本人刚学习这方面代码，不知道是不是改错了，如有错误之处请指正。谢谢！

**Comment by SeanChenxy** [comment]
你好。非常感谢你的建议。问题1我已经修正了，问题2、3可能是与python版本有关，可以按照你的方式修改。关于freihand读取的问题，我没有复现这个错误。但是我更新了一下freihand.py，建议直接运行这个py文件调试数据集的问题，保证数据读取正确后再运行训练或测试脚本。（ps. rgb2不需要处理，正常情况下不会使用rgb2）。后续问题可以继续在这里讨论，谢谢。

**Comment by Whiskysu** [comment]
你好，非常感谢您的回复！我按照你说的更新了freihand.py后，然后调试freihand.py文件，还是会一直报错“AttributeError: 'tuple' object has no attribute 'sort'”。我是按照您的readme.md建议安装了在Ubuntu20上安装了虚拟环境handmesh，其中python3.6，pytorch1.7.1，我在两台电脑上都是这个结果。是不是因为freihand.py运行是需要在python2环境下？
顺便问一下您跑这个轻量化的网络在什么配置下需要多久？

下图是python3.6以及pytorch1.7.1。
![image](https://user-images.githubusercontent.com/46953515/146554328-a3780af9-6cd8-4e3f-8788-a3e84891ab38.png)

下图是报错结果
![2021-12-17 21-47-28屏幕截图](https://user-images.githubusercontent.com/46953515/146554058-f78a6792-f6df-4aa5-9548-82989a2429e8.png)

下图是调试结果
![image](https://user-images.githubusercontent.com/46953515/146556077-80605674-dde9-4c52-986d-58e3a202d59f.png)

**Comment by SeanChenxy** [comment]
Hi，我运行的环境也是python3.6。关于'tuple' object has no attribute 'sort'，按照你之前的修改方法就行。MobRecon在2080GPU上约14ms。

**Comment by Whiskysu** [comment]
谢谢，我已经修复了这个问题了，我的原因是numpy==1.19.1
scipy==1.4.1
matplotlib==3.3.2
opencv-python==4.4.0.46
这些版本必须完全一致。我之前默认用anaconda更新了这些库的版本，导致了'tuple' object has no attribute 'sort'或者其他的错误。
感谢你的工作！！！
