### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Whiskysu** [SeanChenxy/HandMesh#17]
你好，陈先生，请教两个问题：
第一，请问Freihand数据集没有验证集，验证只能将结果上传服务器得出来，所以你论文中的图中（Camera-Space Hand Mesh Recovery via Semantic Aggregation and Adaptive 2D-1D Registration文章中）的PCK误差是通过Freihand数据集的哪些部分进行evaluation的？
第二，其它方法的AUC是怎么得到的？从这些方法文章中找还是自己做实验跑？以及在RHD上数据集上的PCK误差是只用Freihand数据集训练得到的模型后进行直接在RHD数据集进行evalutation吗？因为你提供了Freihand数据集的Mesh 标签，但是RHD数据集没有。
![image](https://user-images.githubusercontent.com/46953515/148356899-6f3b1171-25eb-437f-a49b-44dbcdf53f64.png)

**Comment by SeanChenxy** [comment]
你好。感谢你的问题。1. FreiHAND的测试服务器能够给出PCK曲线。2. 其他方法的结果基于各自的论文，我并没有复现。上图中RHD的结果有两种，1）直接使用FreiHAND训练的模型，2）FreiHAND训练后再使用RHD的3D pose标签进行finetune。

**Comment by Whiskysu** [comment]
谢谢！
