### ISSUE TITLE
How to get axis-angle in MANO?

### ISSUE THREAD

**Issue by ykk648** [SeanChenxy/HandMesh#19]
I got vertex xyz etc. but how can I get axis-angle or something like rotation matrix?

**Comment by SeanChenxy** [comment]
Hi, this pipeline does not output rotation. There are three ways to get rotation from vertex/xyz: (1) optimize MANO coefficients to align MANO model with the predicted vertex/xyz (https://github.com/CalciferZh/Minimal-IK); (2) train a IKNet to map xyz to rotation (https://github.com/CalciferZh/minimal-hand); (3) close-form computation (Section 3.1 of https://arxiv.org/pdf/2109.11399.pdf).

**Comment by ykk648** [comment]
professional and useful, thank you a lot.

issue close.
