### ISSUE TITLE
demo问题

### ISSUE THREAD

**Issue by wangjiejie2022** [SeanChenxy/HandMesh#20]
您好！demo是输入以手为中心的图片，相机内参根据图片缩放进行变换，如果输入的手在图像中占比很小，不在图像中心，先通过目标检测出手的范围，然后将手的图片传入网络，这样的话相机内参怎么变化呢？

**Comment by wangjiejie2022** [comment]
K[0, 2] = scale*(K[0, 2]-tl_x+0.5) - 0.5      式中为什么要加0.5和减去0.5呢？

**Comment by SeanChenxy** [comment]
实际使用中，0.5的影响不大。可以参考 http://www.noobyard.com/article/p-hywxojbh-rw.html

**Comment by wangjiejie2022** [comment]
> 实际使用中，0.5的影响不大。可以参考 http://www.noobyard.com/article/p-hywxojbh-rw.html

好的，谢谢！
