### ISSUE TITLE
How to generate training_mano.json and evaluation_scale.json file?

### ISSUE THREAD

**Issue by anvesh2323** [SeanChenxy/HandMesh#21]
Can you please tell us how did you generate **_training_mano.json_** and **_evaluation_scale.json_** file?
We need to generate the same for our custom data.
And why are you using training_mano.json, evaluation_scale.json?

**Comment by SeanChenxy** [comment]
Hi, training_mano.json is provided by  [FreiHAND](https://github.com/lmb-freiburg/freihand). We do not generate it, but you can open it with our code and produce another  one with the same style. [json](https://docs.python.org/3/library/json.html) is a good tool that may meet your needs.

**Comment by anvesh2323** [comment]
Hi SeanChenxy, thanks for your time.

 I understood why you are using training_xyz.json and training_K.json, but didnt quite understand the significance of  training_mano.json. Can you tell me what does that file data mean and how it's used here? 

Once I understand what that file means, I may need to generate it for my custom data too. 
I did not quite get what exactly you meant in the last comment 
> ` but you can open it with our code and produce another one with the same style`.

So if you can elaborate more about the steps to generate it, then it would be great!

**Comment by SeanChenxy** [comment]
Hi, for constructing a custom dataset , I suggest following the returned elements to write a new class. https://github.com/SeanChenxy/HandMesh/blob/7d7cf4dce0fbc72bbde8e0a56fd3b8145be3c809/datasets/FreiHAND/freihand.py#L78
You should obtain these tensors in arbitrary ways and the json file is not what you have to use.
