### ISSUE TITLE
Where is the pre-trained models for the demo ?

### ISSUE THREAD

**Issue by sean-001** [SeanChenxy/HandMesh#24]
Hi, SeanChenxy, thanks for your impressive work.

I have tried the demo according to your instructions, but I can't find the pre-trained models. Does it mean that I need to use the models that are trained by myself ?

**Comment by SeanChenxy** [comment]
Hi, you would want to download the files you need from [Google drive](https://drive.google.com/drive/folders/1MIE0Jo01blG6RWo2trQbXlQ92tMOaLx_?usp=sharing).

**Comment by sean-001** [comment]
> Hi, you would want to download the files you need from [Google drive](https://drive.google.com/drive/folders/1MIE0Jo01blG6RWo2trQbXlQ92tMOaLx_?usp=sharing).

Oh, I have found it, thanks !
