### ISSUE TITLE
Image Not found error

### ISSUE THREAD

**Issue by anvesh2323** [SeanChenxy/HandMesh#25]
Hi Sean,
     I have been trying to train the model on our custom data. I have given around 1000 images as input to the model.
Once these images are loaded it says 
```
Loading of 1000 training samples 
Loaded 4000 training samples
```

After this i will be getting image not found error. Lets say `/training/rgb2/00002782.jpg` is not found.

I have observed that [here](https://github.com/SeanChenxy/HandMesh/blob/7d7cf4dce0fbc72bbde8e0a56fd3b8145be3c809/datasets/FreiHAND/freihand.py#L40) you have multiplied 4. 
I wanted to know the reason behind the multiplication by 4.
How should I resolve the above error? , since it's asking the image which is out of our dataset.

**Comment by SeanChenxy** [comment]
Hi, we use `self.db_data_anno *= 4` in freihand.py because FreiHAND used background-changed images (In this way, the image amount is 4-times as much as the annotation amount). So, there is no need to use `self.db_data_anno *= 4`  in a custom dataset.

**Comment by anvesh2323** [comment]
Yeah, thanks for the clarification. :D
