### ISSUE TITLE
Generation of Mesh files

### ISSUE THREAD

**Issue by simple612** [SeanChenxy/HandMesh#26]
Hi Sean, thanks for your wonderful work.
I was trying to train the model with our custom data, and inorder to train the model we require mesh files ( .ply files ).
So, even i also wanted to create mesh  files for our dataset. 
How can I generate those mesh files.?

Thanks in advance :D

**Comment by SeanChenxy** [comment]
Hi, if you have ground-truth vertices, the following

**Comment by SeanChenxy** [comment]
Hi, if you have ground-truth vertices, the following method can be used to generate `.obj` or `.ply`
https://github.com/SeanChenxy/HandMesh/blob/7d7cf4dce0fbc72bbde8e0a56fd3b8145be3c809/run.py#L300

If you do not have ground-truth vertices, you could refer to [FreiHAND](https://openaccess.thecvf.com/content_ICCV_2019/papers/Zimmermann_FreiHAND_A_Dataset_for_Markerless_Capture_of_Hand_Pose_and_ICCV_2019_paper.pdf) to collect data.

**Comment by simple612** [comment]
Hi Sean, thanks for your time.
I dont have ground truth values to generate mesh files.
So, i tried to generate them, but i didnt get it. So if you could help me, it will be great.!!

Thanks :D

**Comment by SeanChenxy** [comment]
Oh, generating ground truth is a non-trivial task. Based my understanding, the most concise manner is 1) generating 2D pose with off-the-shelf library (like [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose)); 2) fitting MANO coefficient with the obtained 2D pose. This method is described by [YoutubeHand](https://openaccess.thecvf.com/content_CVPR_2020/papers/Kulon_Weakly-Supervised_Mesh-Convolutional_Hand_Reconstruction_in_the_Wild_CVPR_2020_paper.pdf) in detail.
