### ISSUE TITLE
手机端推理

### ISSUE THREAD

**Issue by zhang0557kui** [SeanChenxy/HandMesh#28]
请问，有试过Android手机端可以使用MobRecon模型吗，哪种移动端推理框架支持呢

**Comment by SeanChenxy** [comment]
Hi，能够在Android上部署，不过我们用的是快手自研的移动端引擎。

**Comment by zhang0557kui** [comment]
> Hi，能够在Android上部署，不过我们用的是快手自研的移动端引擎。

Thanks for your helpful reply.
