### ISSUE TITLE
Implementation details about consistency loss

### ISSUE THREAD

**Issue by vra** [SeanChenxy/HandMesh#33]
Hi @SeanChenxy ,

For the implementation of consistency loss, I come up two different approaches but don't know which one is the right one used in the paper, could you give some hints on this? Thanks.

## First approach
Use the (image, vertex) from one camera, and then randomly generate a custom T to create paired (image, vertex) as inputs for consistency loss

## Second approach
Use two images at the same time from different camera in dataset (e.g., camera 1 and camera 2 in FreiHAND),  as the input of consistency loss, i.e., no need to generate novel camera, just use already existing ones

**Comment by SeanChenxy** [comment]
Hi, we use the first approach. (ps. the code of this part will be released before the conference.)
