### ISSUE TITLE
绝对三维坐标

### ISSUE THREAD

**Issue by wangjiejie2022** [SeanChenxy/HandMesh#36]
mobrecon可以得到手的绝对三维坐标吗

**Comment by SeanChenxy** [comment]
可以的，通过以下函数计算https://github.com/SeanChenxy/HandMesh/blob/47e860cc046e4d36aad244fb8291e4ccf59a32a9/mobrecon/tools/registration.py#L20

**Comment by Stephenfang51** [comment]
@SeanChenxy 你好 额外请教 得到的绝对坐标 原点在那里呢？ 在摄像头的位置吗 谢谢 ！

**Comment by SeanChenxy** [comment]
是的，以相机位置为原点

**Comment by wangjiejie2022** [comment]
> 是的，以相机位置为原点

好的，谢谢您的回复！
