### ISSUE TITLE
关于数据集问题

### ISSUE THREAD

**Issue by Stephenfang51** [SeanChenxy/HandMesh#38]
作者你好

论文中提到额外利用的maya制作数据集
没有考虑使用实际相机拍摄的原因是为什么呢？ 还是因为实际拍摄需要用多视角相机解决视角问题， 成本考虑吗？

如果制作数据集想以实际的照片拍摄的话， RGB采集是不是以多视角采集更好（类似FreiHAND的思路）？
但是三维关键点应该如何进行标注呢？ 找了一轮没有找到类似的标注的软件

又或者是用深度相机转成点云图进行标注？

望作者拨空可以给予建议 谢谢！

**Comment by SeanChenxy** [comment]
你好，拍摄真实数据是可以的，一般有两种方式：1）多视角RGB，标注2D pose，再通过三角化获得3D pose。2）采集深度，转化为点云，标注少量关键点，再用MANO去拟合。这两种方式都很难精确标注，且误差与硬件的质量有关。FreiHAND的标注质量很不错，但受限制于多目采集设备，缺乏背景和光照多样性。我们采用虚拟数据的主要原因是成本低，标注没有误差，hand pose、背景、光照可控。

**Comment by Stephenfang51** [comment]
@SeanChenxy 非常谢谢回复 ！ 您在这方面的工作很专业！
