### ISSUE TITLE
请问有什么方法可以只获得精确的root relative 3d pose 而不用通过mesh的方法吗 ？

### ISSUE THREAD

**Issue by Rookienovice** [SeanChenxy/HandMesh#39]
作者您好，很棒的工作，请问关于camera space那篇文章的做法，如果我想只估计出root relative 3D pose 而不用得到mesh，有什么比较合理的方法得到更高的精度吗？还有在这种情况下，root depth 怎么获得比较合适？

**Comment by SeanChenxy** [comment]
你好，可以尝试 https://github.com/CalciferZh/minimal-hand，不使用这里面的IKNet即可获得 root relative 3D pose。计算 root depth 之前还需要估计2D pose,再通过PnP方法估计。

**Comment by Rookienovice** [comment]
感谢您的回复！这篇我实验过了，现在我想采用2.5D估计的方式，分别预测 uv 和 root-relative depth，然后得出root relative 3D pose，请问如果采用这种方法的话，怎样可以得到更好的精度？

**Comment by SeanChenxy** [comment]
哦，刚才我理解错了。可以参考 https://github.com/mks0601/I2L-MeshNet_RELEASE?utm_source=catalyzex.com ，他把relative depth 构造为一个1D heatmap。

**Comment by Rookienovice** [comment]
这种1D heatmap直观上来看是不是可能会丢失空间信息？作者您论文的语义聚合策略，您感觉对直接3 d pose 估计有帮助吗？

**Comment by SeanChenxy** [comment]
相比于直接以m为单位回归relative deth, 我认为 1D heapmap 是一种更好的建模方式：monocular depth 存在很强的2D-3D ambiguity，1D heatmap能够建模其中的不确定性。并不存在1D heatmap丢失空间信息。CMR中的sub-pose、MobRecon中的MapReg、以及一些graph方法都是在建模点与点之间的关系，对估计relative depth是会有帮助的。

**Comment by Rookienovice** [comment]
谢谢您的解答！对我很有帮助，期待着您后面的研究，祝您工作顺利！

**Comment by Rookienovice** [comment]
作者您好，我想请问一下关于手部mesh预测的问题，采用回归MANO参数 和 vertex-based 的方法各自的优缺点都有哪些啊? 比如预测的准确性，效率等。

**Comment by SeanChenxy** [comment]
估计MANO系数：（1）pipeline的设计可以很灵活，比如IK、约束手部生理结构（2）beta参数过于抽象、优化难度很大（3）CNN并不擅长优化旋转，最近有很多工作尝试去解决这个问题。
估计vertex：（1）避免了优化旋转，同时引入了很强的空间几何关系，精度比回归MANO系数更好（2）graph方法引入了一些memory access，导致GPU并行计算效率低。
共同缺点：只能处理固定的几何拓扑。

**Comment by Rookienovice** [comment]
感谢您的解答，对我理解很有帮助！我还有一个困惑，现在基于单目RGB图像的 3d hand pose estimation 是不是大都是估计相对的3d pose（也就是root - relative  3d pose），而不是手部相对于相机的绝对位置？如果我想估计手部的绝对位置，采用分别估计root-relative 3d pose 和 root 绝对深度的方案，那这个root绝对深度分支该怎么设计比较合理？还有这种root-relative 3d hand pose和绝对的3d hand pose 在实际应用中都有哪些以及不同啊 ？

**Comment by SeanChenxy** [comment]
理论上，root的绝对深度是不能通过monocular RGB估计出来的，所以一般采用2D-3D PnP的方法获得root。但是，PnP其实也只能获得2D-3D对齐意义下的root，而不是真实值。想要获得真实值，还需要借助一些先验，比如我们提前知道手部骨骼长度，并在PnP之前用于归一化root-relative 3d pose。实际应用中，类似虚拟人驱动任务只需要root-relative 3d pose，而类似于VR手势操作的应用需要camera-space 3d pose。

**Comment by Stephenfang51** [comment]
@SeanChenxy  作者您好， 看到讨论到相对深度的问题， 突然想到您这自己做的数据集（论文中提到maya制作的）里面的关键点是否也都是相对深度？比如基于手腕的， 而手腕的位置是在原点， 或者是绝对的坐标呢？ 谢谢！

**Comment by SeanChenxy** [comment]
Hi，在制作手部几何模型时，以手腕为原点，可以理解为每个点的depth都是root-relative的。在渲染之前，我们可以把手部几何模型放到空间中的任意位置，因此可以获得root的绝对坐标。

> @SeanChenxy 作者您好， 看到讨论到相对深度的问题， 突然想到您这自己做的数据集（论文中提到maya制作的）里面的关键点是否也都是相对深度？比如基于手腕的， 而手腕的位置是在原点， 或者是绝对的坐标呢？ 谢谢！

**Comment by Rookienovice** [comment]
谢谢作者的解答，您在这方面很专业，我学习到了很多，感谢。

**Comment by Rookienovice** [comment]
作者您好，请问MANO参数恢复的手部是在以手部为中心的空间中吗？它是怎么对齐到图像空间中的呢？还有为什么我看到很多论文中beta参数的预测只采用L2正则效果就很好了？CNN优化旋转的工作，还有约束手部生理结构的，作者您有什么论文可以推荐看看吗？另外，作者您 MobRecon 中也是和CMR一样，先预测root-relative mesh 在恢复绝对深度吗？

**Comment by SeanChenxy** [comment]
(1) MANO坐标系的原点不在手腕，不过通常会减去手腕关键点使之表达在手腕坐标系下。（2）同样是2D-3D对齐的方式。（3）beta比较抽象，网络很难学好，给个L2正则的目的是使shape尽量接近template，beta的norm太大可能出现很奇怪的shape。（4）Projective Manifold Gradient Layer for Deep Rotation Regression，Weakly Supervised 3D Hand Pose Estimation via Biomechanical Constraints。（5）是的。

**Comment by Rookienovice** [comment]
谢谢作者您的解答，我学到了很多。有几个问题还想请教一下您，（1）这种约束手部生理结构的方式是不是更多用在弱监督中，如果有3D Mesh GT监督的话，用生理结构约束的话，收益不是很大？（2）作者您CMR论文中提到您在FreiHAND数据集中训练的模型在RHD数据集中测试后泛化性很好，而我实验着其他一些模型在真实数据和仿真数据中的泛化性不是很好，作者您认为您的模型这么好的泛化性原因是什么？（3）还有这种vertex-based方法是不是很依赖于Mesh GT，而Mano-bsed的方法反而可以通过弱监督的方式去优化？作者您两篇中都采用vertex-based的方式是不是主要就是考虑到其优化简单、引入空间几何关系，并且精度比回归MANO系数更好？

**Comment by Stephenfang51** [comment]
@SeanChenxy  再次打扰一下作者， 我想请问仿真数据在您这边实际使用是怎么与其他开源数据例如 FreiHAND做训练的， 我同样用渲染软件做了类似的仿真数据，只在上面训练， 模型本身拟合没有任何问题， 不过迁移到真实场景效果很差（这个应该是必然的）， 是否联合FreiHand一起训练或是有什么建议可以得到吗， 谢谢 ！

**Comment by SeanChenxy** [comment]
我们使用虚拟数据+FreiHAND的学习过程还挺正常。如果有问题可以从两个方面分析：（1）RGB gap，可以采用style transformation方法处理（e.g., https://github.com/vidursatija/PhotoWCT）。（2）pose domain gap，e.g., 可能需要统一两个数据集的骨骼长度为同一种分布。

**Comment by Rookienovice** [comment]
作者您好，关于CMR中root估计问题，那个1D的求解 是不是就是约束2D mesh 和 contours 投影到直线上范围内两个端点要大体一致？还有，一般情况下是不是都是用2d pose和3d pose对齐后的root作为估计值，也就是预测误差大于0.06的时的解（这个0.06单位是米吧？），我看着作者您放出的mobrecon的demo也是只采用pose对齐后的解，是pose对齐后求出的root就足够使用了吗？还有这个估计出的 root 值在您的实际应用中或者说在一些实际应用中，误差是在可接受的范围内吗

**Comment by Stephenfang51** [comment]
@SeanChenxy 感谢专业又慷慨的分享 ！

**Comment by EAST-J** [comment]
> (1) MANO坐标系的原点不在手腕，不过通常会减去手腕关键点使之表达在手腕坐标系下。（2）同样是2D-3D对齐的方式。（3）beta比较抽象，网络很难学好，给个L2正则的目的是使shape尽量接近template，beta的norm太大可能出现很奇怪的shape。（4）Projective Manifold Gradient Layer for Deep Rotation Regression，Weakly Supervised 3D Hand Pose Estimation via Biomechanical Constraints。（5）是的。

您好，我对于MANO的坐标系一直有些疑惑，所以想请教您一下，请问MANO坐标系和相机坐标系或者世界坐标系之间是如何转换的呢，他们之间的关系是什么？并且我想请问一下提供的freihand_mesh_gt是在相机坐标系下的，他是基于freihand的mano参数生成的吗？
