### ISSUE TITLE
Code for CMR_PG

### ISSUE THREAD

**Issue by deyingk** [SeanChenxy/HandMesh#4]
Hi Xingyu, thanks for your great work and releasing the code!
Would you please also release the code for the CMR-PG model used in the paper, if possible? Thanks!

**Comment by SeanChenxy** [comment]
Hi, I have added this model. You can use it by modifying `demo.sh` with `model='cmr_pg', exp_name='cmr_pg', resume 'cmr_pg_res18_freihand.pt'`

**Comment by deyingk** [comment]
Thanks!
