### ISSUE TITLE
What is _K.npy?How to get _K.npy of my own image? 

### ISSUE THREAD

**Issue by tankchenggeng** [SeanChenxy/HandMesh#40]
I want to run the demo with my own image, but I have no _K.npy for image

**Comment by SeanChenxy** [comment]
Hi, please refer to https://github.com/SeanChenxy/HandMesh/issues/7

**Comment by tankchenggeng** [comment]
Thanks for you reply. I used the default value [[500, 0, 112.36], [0, 500, 112.36], [0, 0, 1]] and good the acceptable result. Thanks!
