### ISSUE TITLE
visible probability prediction  of keypoints

### ISSUE THREAD

**Issue by vra** [SeanChenxy/HandMesh#42]
Hi Xingyu,
I want to predict the visibility score of 21 keypoints on image space based on CMR or MobRecon. However I don't get a clean idea about how to creating ground truth label of keypoints visibility on FreiHAND dataset. What I want to do is when some keypoints are occluded by others (like inner keypoints in wist pose) or out of image, then set its score to a low value.  Could you give any hints on this? Thanks in advance.

**Comment by SeanChenxy** [comment]
Hi, Yunfeng. I have no good idea to automatically annotate visibility. It feels like the visibility, or confidence, can be estimated with likehood method. For each joint landmark, we can estimate its distribution with mean and variance.  Then, use negative log-likelihood to train. That is, put GT into the distribution, and maximize the probability. In this way, we do not need extra annotation, and the predicted variance could reflect the confidence/visibility.

**Comment by vra** [comment]
Hi Xingyu, thanks for your solution. I don't know much about probability-related deep learning models thus I will do further search about it. Thanks again for your generous help
