### ISSUE TITLE
cmr-human36m

### ISSUE THREAD

**Issue by liwang0621** [SeanChenxy/HandMesh#43]
hi，
我想尝试跑一下这里human36m的demo和训练，但是都没有成功，训练的时候在这里报错 [link](https://github.com/SeanChenxy/HandMesh/blob/47e860cc046e4d36aad244fb8291e4ccf59a32a9/cmr/datasets/Human36M/human36m.py#L306)，我理解这里的rot应该是一个数，但是在[link](https://github.com/SeanChenxy/HandMesh/blob/47e860cc046e4d36aad244fb8291e4ccf59a32a9/cmr/datasets/Human36M/human36m.py#L279)这里返回的rot是个array，我修改为rot = rot[0]可以正常训练
另外我想跑一下human36m的demo，但是报错如下
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/81345643/176805040-09241d96-1081-46de-9879-d60bbf916440.png">

刚开始做mesh相关的工作，这里的问题我实在不知道怎么解决了

**Comment by SeanChenxy** [comment]
你好，rot=rot[0]是正确的操作，可能是我更新mobrecon后没有更新human3.6M的dataset。报错的原因是vertex2xyz和uv_select的维度没对上，可以debug看看是多少，应该都是17才对。
