### ISSUE TITLE
补充数据集的3D pose问题

### ISSUE THREAD

**Issue by jackyyang9** [SeanChenxy/HandMesh#44]
陈先生你好，

您在MobRecon论文中的图13展示了补充数据集的annotations，可是我下载后发现只有mesh，请问能不能提供论文中提到的annotations呢？谢谢。

**Comment by SeanChenxy** [comment]
你好，抱歉我目前无法release其他数据。joints 是可以通过mesh得到的，[这里](https://github.com/SeanChenxy/HandMesh/blob/main/mobrecon/datasets/comphand.py)有相关操作。depth也可以通过对mesh的渲染得到，可以参考[pyrender](https://pyrender.readthedocs.io/en/latest/)的使用方法。

**Comment by jackyyang9** [comment]
十分感谢您的回复，我从comphand.py中找到了相关代码，得到了下面的结果：

![image](https://user-images.githubusercontent.com/108614973/177171071-5c990b8b-a19c-475c-8d1b-da2a47fe52fa.png)

谢谢！

但我想确认一下代码中的joints，即get_training_sample()的return的 joint_cam是MANOHandJoints类的吗？

还有，上图中kps3d2d和kps2d有什么不同呢？视觉效果上好像看不出来。期待您的回复。

**Comment by SeanChenxy** [comment]
joint_cam 是3D joint坐标，不是MANOHandJoints。kps2d 是2D 关键点，kps3d2d是3d关键点的投影，在这个数据集里是完全相同的
