### ISSUE TITLE
BugReport in function drawmesh

### ISSUE THREAD

**Issue by jingshuangliu22** [SeanChenxy/HandMesh#46]
Dear author,

I found a bug in the function [drawmesh](https://github.com/SeanChenxy/HandMesh/blob/47e860cc046e4d36aad244fb8291e4ccf59a32a9/utils/draw3d.py#L81).  The image shape is H x W x 3, but the parameters of 'set_size_inches' is (width, height) according to the matplotlib [API](https://matplotlib.org/3.3.4/api/_as_gen/matplotlib.figure.Figure.html). So I suppose that the correct input of 'set_size_inches' should be image.shape[1], image.shape[0]. If I were right, there maybe some same bugs in other functions. Please check them out.

Best wishes,
Jingshuang

**Comment by SeanChenxy** [comment]
Thanks for your mention. We will fix this bug.
