### ISSUE TITLE
pretrained模型与train过程所得模型之间的差异

### ISSUE THREAD

**Issue by Serendipiy2021** [SeanChenxy/HandMesh#47]
您好，陈先生，您的mobrecon算法在手部重建方面取得快且准确的效果，于是我想要复现您的工作以便于学习。在算法训练的过程中，遇到了一些问题，希望得到您的指点。通过FreiHand数据集直接训练desestack.path得到checkpoint_best.pt与checkpoint_last.pt与您开源的预训练网络结构有所差异，具体体现在：我用checkpoint_best.pt与checkpoint_last.pt替换您的预训练网络时，model load部分会出现
missing key(s) in state_dict : "backbone.conv.0.weight".
             Unexpected key(s) in state_dict : "backboone.reduce.0.weight" , "decoder3d.de_layer_conv.0.weight"
请问这种问题的出现是我在训练过程中有什么没有注意的的错误吗？

**Comment by SeanChenxy** [comment]
应该是版本问题，预训练的weight对应cmr文件夹下的mobrecon，是去年release的版本。代码重新整理后放在mobrecon文件夹下，新训练的weight不需要与预训练的weight对齐。

**Comment by Serendipiy2021** [comment]
> 应该是版本问题，预训练的weight对应cmr文件夹下的mobrecon，是去年release的版本。代码重新整理后放在mobrecon文件夹下，新训练的weight不需要与预训练的weight对齐。



好的，谢谢您的解答，那有没有什么快速的方法能够将新训练的模型进行可视化的效果展示呢？因为mobrecon的demo是cmr文件夹下进行的

**Comment by SeanChenxy** [comment]
最快的方法是对应修改一下cmr文件夹下的mobrecon模型文件。
