### ISSUE TITLE
mask_predict置信度太低

### ISSUE THREAD

**Issue by lvZic** [SeanChenxy/HandMesh#50]
cmr-pg-FreiHAND，在真实场景下测试，mask_pred 的值都是0
                   mask_pred = (mask_pred[0] > 0.3).cpu().numpy().astype(np.uint8)

这里0.3换为0.1 ，mask_pred依然都是0，奇怪的是手指坐标值都有，是哪里的问题呢？

**Comment by SeanChenxy** [comment]
根据这些信息难以找到问题，建议debug一下。cmr-g对真实场景的繁华性能好一些。

**Comment by lvZic** [comment]
> 根据这些信息难以找到问题，建议debug一下。cmr-g对真实场景的繁华性能好一些。

直接运行./cmr/scripts/demo_cmr.sh  FreiHAND的测试图片结果也是poly = None


![3891_plot](https://user-images.githubusercontent.com/7788572/180352618-dfb121c9-8411-4edc-b5cc-13e6c02e3dd7.jpg)
![3871_plot](https://user-images.githubusercontent.com/7788572/180352625-bbe582c6-4007-401c-98b1-d08d437f4804.jpg)
![3790_plot](https://user-images.githubusercontent.com/7788572/180352645-71400087-8ed0-4520-9241-cad32cce55d7.jpg)

**Comment by lvZic** [comment]
the reason is  "sort(key=cnt_area, reverse=True)" need list object while contours is tuple. Using sorted instead of sort sovled it.

**Comment by yuyu19970716** [comment]
您好，我也遇到了和您一样的问题，没有mask，不过我没看懂您说的原因是什么意思，如何解决的，请问能详细说一下吗？非常感谢！
