### ISSUE TITLE
mobrecon eval issue

### ISSUE THREAD

**Issue by CVStack** [SeanChenxy/HandMesh#51]
Hi. Thank you for sharing your code. Your paper is very impressive.

But I wonder why the code needs the mask of FreiHAND when evaluating the model.

I understood your model only use the mesh in measurement.

Can you explain this problem?

Thank you!

![image](https://user-images.githubusercontent.com/38209962/181139168-13a295e6-b670-4956-9390-081847a5fe78.png)

**Comment by SeanChenxy** [comment]
Hi，mask is not used in evaluation process, you don’t need to return it.

**Comment by CVStack** [comment]
Oh! I got it. Thank you! :)
