### ISSUE TITLE
补充数据集的单位问题

### ISSUE THREAD

**Issue by jackyyang9** [SeanChenxy/HandMesh#52]
作者你好，我对补充数据集的人手mesh的单位有疑问，obj文件里边的单位和输出的关节点一样都是米吗？
如果是的话，我发现里边的点的甚至存在某些点的某一维度的坐标有0.8米的情况，所以我觉得mesh中点的单位不是米。
所以如果我想将单位化成米的话需要如何操作呢，和comphand.py中处理三维关节点的操作是一样的吗？

**Comment by SeanChenxy** [comment]
你好，单位是m，但是这是相机坐标系的坐标，比如 0.8 可能表示手距离相机的深度为0.8m

**Comment by jackyyang9** [comment]
十分感谢，我明白了。
