### ISSUE TITLE
How to use my own dataset

### ISSUE THREAD

**Issue by XIANGLINYUN** [SeanChenxy/HandMesh#54]
你好，我想请问一下，我应该怎样去使用我自己的数据集测试呢

**Comment by SeanChenxy** [comment]
你好，参考以下格式读取测试集图像，不需要使用真实的相机参数（see #7） 
https://github.com/SeanChenxy/HandMesh/blob/95ea000ed3b95a50391022f72a24173dfe440ff0/mobrecon/datasets/freihand.py#L242
用这个flag进行可视化
https://github.com/SeanChenxy/HandMesh/blob/95ea000ed3b95a50391022f72a24173dfe440ff0/mobrecon/runner.py#L322

**Comment by XIANGLINYUN** [comment]
> 你好，参考以下格式读取测试集图像，不需要使用真实的相机参数（see #7）
> 
> https://github.com/SeanChenxy/HandMesh/blob/95ea000ed3b95a50391022f72a24173dfe440ff0/mobrecon/datasets/freihand.py#L242
> 
> 
> 用这个flag进行可视化
> https://github.com/SeanChenxy/HandMesh/blob/95ea000ed3b95a50391022f72a24173dfe440ff0/mobrecon/runner.py#L322

谢谢！
