### ISSUE TITLE
Some questions about two-dimensional backbone network

### ISSUE THREAD

**Issue by yuyu19970716** [SeanChenxy/HandMesh#56]
Hi Xingyu, thank you very much for your contribution!
     I have another question, in DenseStack_Backnone, I want to match the code with the paper, I don't know which piece of code the two-dimensional encoder and decoder and channel cascade correspond to? Is the final latent the Fe in the paper? uv-reg is Lp?

**Comment by yuyu19970716** [comment]
Do you know about deep completion? Do you know if there are any relevant datasets for deep completion of hand parts? For example: input is rgb and sparse depth map, groundtrutu is a dataset of dense depth maps.
   Very much looking forward to your reply! Thanks in advance!

**Comment by SeanChenxy** [comment]
Hi, `class DenseStack_Backnone` is a hourglass structure. It contains 2D encoding and MapReg in Figure 2. So, `latent` is F^e, and `uv_reg` is L^p. I am sorry that I have little knowledge on completion.

**Comment by yuyu19970716** [comment]
> Hi, `class DenseStack_Backnone` is a hourglass structure. It contains 2D encoding and MapReg in Figure 2. So, `latent` is F^e, and `uv_reg` is L^p. I am sorry that I have little knowledge on completion.
Thank you very much for your prompt reply!
