### ISSUE TITLE
Could the dense mesh be provided

### ISSUE THREAD

**Issue by jingshuangliu22** [SeanChenxy/HandMesh#57]
Dear Author,
In the 13/17 of the paper, you mentioned that _As shown in Figure 13, we provide annotations of our designed dense mesh, MANO-style mesh, 3D pose, 2D pose, silhouette, depth map, and intrinsic camera parameters._ I wondered if the _dense mesh_ could be provided in order to reproduce the results.
Thanks a lot.

**Comment by SeanChenxy** [comment]
I am sorry that I cannot get other data because of the change of my employment.
