### ISSUE TITLE
FPS达不到论文效果

### ISSUE THREAD

**Issue by sysu19351054** [SeanChenxy/HandMesh#59]
你好，同样是使用2080Ti的GPU，我用mobrecon模型在FreiHAND上的测试FPS只能达到39.4。可以请问一下论文测FPS的具体设置吗？

**Comment by SeanChenxy** [comment]
你好。具体设置就是code中的设定。问题可能在于CPU和memory access，DSConv和mesh upsample都是对GPU并行不友好的操作，推理速度可能会受限于内存访问。

**Comment by jinfagang** [comment]
@SeanChenxy 预测一张图要25ms吗？这么慢的吗，那还叫mobierec

**Comment by SeanChenxy** [comment]
pytorch只是实验性平台，想要产品化还请使用更高效的推理引擎

**Comment by jinfagang** [comment]
GPU都这么慢，更别说CPU了，最好不要随便取名叫Mobrecon 这么慢的速度。

**Comment by SeanChenxy** [comment]
> GPU都这么慢，更别说CPU了，最好不要随便取名叫Mobrecon 这么慢的速度。
非常感谢你的建议，期待你提出更好的解决方案，为领域做出贡献

**Comment by vra** [comment]
> GPU都这么慢，更别说CPU了，最好不要随便取名叫Mobrecon 这么慢的速度。

如果你看过论文的摘要的话，可以看到：
> Overall, our hand reconstruction framework, called MobRecon, comprises affordable computational costs and miniature model size, which reaches a high inference speed of **83FPS** on Apple A14 CPU.

在A14芯片的手机上能达到83FPS，因此叫我个人任务叫MobileRecon是没有问题的。而且快手app的一些玩法[1]已经应用了这篇论文中的算法，实时性没有问题

[1] https://mp.weixin.qq.com/s/8sA_XGlqSejho2XEZ9JNLQ
