### ISSUE TITLE
about RHD and other datasets without mesh gt 

### ISSUE THREAD

**Issue by EEWenbinWu** [SeanChenxy/HandMesh#6]
How to train model on FreiHand and other datasets（like RHD） without mesh gt together？

**Comment by SeanChenxy** [comment]
Hi, if without mesh GT, you can use 3D pose for supervision, like Eq. 9 in [I2L-MeshNet](https://arxiv.org/pdf/2008.03713.pdf). And then set vertex loss as 0.
