### ISSUE TITLE
I cannot  download the files from google drive

### ISSUE THREAD

**Issue by TheRunningHorse** [SeanChenxy/HandMesh#60]
![屏幕截图 2022-08-22 152157](https://user-images.githubusercontent.com/62589403/185862776-b1805726-042a-43a6-bb9b-7dba3f986dc2.jpg)
 i have tried Chorm bowser

**Comment by SeanChenxy** [comment]
Hi, please try to use [Baidu cloud](https://pan.baidu.com/s/12X1qsuxO2j8jGl6QWJdV6A?pwd=rc4x#list/path=%2F)
