### ISSUE TITLE
ModuleNotFoundError: No module named 'psbody'

### ISSUE THREAD

**Issue by jinfagang** [SeanChenxy/HandMesh#61]
ModuleNotFoundError: No module named 'psbody'

please remove psbody as Mesh lib, this lib is outdated and not support macOS, very hard to install.

**Comment by SeanChenxy** [comment]
Thanks for your sugesstion. I will update it later. Based on https://github.com/MPI-IS/mesh, I have install this package on macOS without any other tricks.

**Comment by jinfagang** [comment]
@SeanChenxy 
I suggest you install on more decent macOS M1. No way to install, also , this lib installed on ubuntu also cubersome. I will avoid use such outdated lib if I were u.
