### ISSUE TITLE
why prediction need K?

### ISSUE THREAD

**Issue by jinfagang** [SeanChenxy/HandMesh#62]
I wasted 2 hours on this useless repo, in prediction, it even need K, how could this possible used for hand estimation in wild?

**Comment by SeanChenxy** [comment]
https://github.com/SeanChenxy/HandMesh/issues/7. There are many better repos (e.g., https://github.com/facebookresearch/frankmocap), which could save your time.

**Comment by jinfagang** [comment]
thank u. using default K solved this problem.  what's the backwards in real world applications such as videos from internet by fixing a default K when inference?
