### ISSUE TITLE
 [CMR] 世界坐标系到相机坐标系的转换

### ISSUE THREAD

**Issue by vra** [SeanChenxy/HandMesh#63]
Hi Xingyu,
请教一下CMR这篇论文中的一个核心点是将在世界坐标系比较难学的重建问题转换到相机坐标系，一般来说，这个转换过程应该包含R和t两个值，想请教下两个问题：
1. 在训练数据集上，怎么得到R和t的gt来将3D标注转换到相机坐标系呢
2. 在自己的没有R和t的测试数据上，有办法将网络输出得到的相机坐标系的3D点转换到世界坐标系吗

再次感谢开源如此有用的代码实现。

**Comment by SeanChenxy** [comment]
你好。
1. 实际上我们只建模了t，R隐含在vertex坐标中。而 t 的GT就是第0个3D 关键点的坐标
2. CMR 的registration就是解决这个问题，利用2D关键点和silhouette 计算 t

**Comment by vra** [comment]
好的，理解了，感谢解答
