### ISSUE TITLE
There is no MASK in the output result

### ISSUE THREAD

**Issue by yuyu19970716** [SeanChenxy/HandMesh#66]
Hello!
    When I run the DEMO or evaluate code about Mobrecon, there is no MASK in the output file. What is the reason?
![image](https://user-images.githubusercontent.com/76560812/190584792-6d5ead97-6fd6-4591-bf66-a307607ddebf.png)

**Comment by SeanChenxy** [comment]
Hi, MobRecon does not predict mask.

**Comment by yuyu19970716** [comment]
Thank you so much for such a quick reply!
Because I want to do 3D reconstruction based on the prior knowledge of the hand and the sparse point cloud data of the lidar, I currently have the data of the lidar, and I want to use the joint point information output in Mobrecon to find the corresponding radar data, I want to know, Can I know the coordinates of each predicted joint point information in the image and can I get it directly?
The second question is, can I add the part that calculates the Mask in Mobrecon? How would I probably need to do it?
I am very much looking forward to your reply!
Thanks in advance!

**Comment by yuyu19970716** [comment]
Thank you so much for such a quick reply!
The second question is, can I add the part that calculates the Mask in Mobrecon? How would I probably need to do it?
I am very much looking forward to your reply!
Thanks in advance!

**Comment by SeanChenxy** [comment]
Sure, you could add another output channel in 2D pose decoder, and use BCE loss to learn from mask GT. This design is similar to CMR:
https://github.com/SeanChenxy/HandMesh/blob/dbdca0d4fba75d7b010762edd4499b8102e06071/cmr/models/cmr_sg.py#L135

**Comment by yuyu19970716** [comment]
Thank you very much for your reply!
I want to know that I can get the coordinate information with the camera position as the origin through the registration() function, that is, the depth information of the key points. Can I get it?

**Comment by yuyu19970716** [comment]
Also I would like to ask, is it accurate enough for absolute 3D coordinates? Because it is only obtained from rgb images, it lacks depth information that can be referenced.

**Comment by SeanChenxy** [comment]
Hi, accurate depth information of keypoints can be obtained. However, you must use the accurate camera intrinsics in registration().

**Comment by yuyu19970716** [comment]
OK! Thank you very much for your reply! wish you a happy life!

**Comment by yuyu19970716** [comment]
Hello, there is still a question I want to ask, do you mean to modify the built-in parameters fx,fy,cx,cy of your own camera for the accurate internal parameters of the camera:
![image](https://user-images.githubusercontent.com/76560812/190995546-7632c6dd-90aa-4b65-a0ae-695411383b14.png)

How to determine the npy file?
Or that I don't need to care about the npy file, just modify K to my own camera parameters? I've read other people's responses to this question, and I'm still confused.

**Comment by SeanChenxy** [comment]
Hi, you don't need to care about the npy file. At first, you would like to get your camera intrinsics:
https://github.com/SeanChenxy/HandMesh/blob/dbdca0d4fba75d7b010762edd4499b8102e06071/mobrecon/datasets/comphand.py#L48
Then, the camera intrinsics (focal and princpt) should be modified according to hand detection box:
https://github.com/SeanChenxy/HandMesh/blob/dbdca0d4fba75d7b010762edd4499b8102e06071/mobrecon/datasets/comphand.py#L224

**Comment by yuyu19970716** [comment]
Thanks again for your reply!
In order for me to understand your statement more precisely:
I would like to confirm with you that I need to modify the following places in total:
I think I need to modify /Mobercon/mobrecon/datasets/comphand.py and freihand.py at the same time when training: For comphand.py, modify it as you said. Like in freihand.py: def get_training_sample(self, idx)::

![1663644678832](https://user-images.githubusercontent.com/76560812/191161343-999988cb-efe1-4f8d-b900-a5a45b84c759.png)

I need to modify /Mobercon/cmr/datasets/FreiHAND/freihand.py for my evaluation: def get_eval_sample(self, idx):
![1663644649073](https://user-images.githubusercontent.com/76560812/191161290-27a4c2f7-fe44-483f-a9a5-96a597d2abc5.png)


When I run the demo to test my own dataset, I also need to modify the following part of /Mobercon/cmr/runer.py:
![1663644628008](https://user-images.githubusercontent.com/76560812/191161252-75d67f75-1dad-43c1-a83d-0acbfe1c346f.png)



I'm very troublesome for you to help me look at it patiently. Are the places I mentioned facing?
Because I feel that what you said last time may only be the part in comphand.py that needs to be modified during training, so I have to trouble you again to help me determine what other places I need to modify?
Sorry to bother you again, thanks in advance! ! !

**Comment by SeanChenxy** [comment]
Hi, if I understand correctly, you don't need to re-train a model. So, only cmr/runer.py should be modified. First, K=load('your_K'). Second, get detection box of hand. Third, use the below code to crop your image and get new K
https://github.com/SeanChenxy/HandMesh/blob/dbdca0d4fba75d7b010762edd4499b8102e06071/cmr/datasets/FreiHAND/freihand.py#L58

ps, Sorry that the above code reference is differnet from previous mentioned one. I recently find it is a more concise version.

**Comment by yuyu19970716** [comment]
OK! thank you very much!
I really just need to test it at the moment! Thanks again for your reply! wish you a happy life!

**Comment by yuyu19970716** [comment]
OK! thank you very much!
I really just need to test it at the moment! Thanks again for your reply! wish you a happy life!
