### ISSUE TITLE
Converting to .npy for test images

### ISSUE THREAD

**Issue by selorm4u** [SeanChenxy/HandMesh#67]
Hello SeanChenxy, can you kindly direct me to the code you executed to generate the .npy files for the test images you used? I have my custom dataset and want to test them but I am unable to generate the equivalent .npy for them. Any feedback is greatly appreciated.

**Comment by SeanChenxy** [comment]
Hi, if you do not need a accurate K, you can use a default K (see #7). Otherwise, please use following code to extract hand RoI and its K (i.e., my npy file).  https://github.com/SeanChenxy/HandMesh/blob/dbdca0d4fba75d7b010762edd4499b8102e06071/cmr/datasets/FreiHAND/freihand.py#L58
