### ISSUE TITLE
I used my own data set for testing, the effect is poor

### ISSUE THREAD

**Issue by yuyu19970716** [SeanChenxy/HandMesh#69]
Hello, I use my own data set for testing.I cropped the hand part of the image for testing. The data set is all gloves, but the effect is very bad. What is the reason?
![image](https://user-images.githubusercontent.com/76560812/196326488-ea6231ea-4dae-49ac-8013-3b4a69e0c9a9.png)
![image](https://user-images.githubusercontent.com/76560812/196326528-bc0db173-2468-4a80-9f14-e3a62a1e5b10.png)
![image](https://user-images.githubusercontent.com/76560812/196326547-c1a0f71a-ecf1-4112-9e83-92aa21a2f50a.png)
![image](https://user-images.githubusercontent.com/76560812/196326564-ec416b28-72e8-417b-a7bd-1f0efb2840ca.png)

**Comment by SeanChenxy** [comment]
Hi, the pre-trained model cannot handle glove data.

**Comment by yuyu19970716** [comment]
Thank you very much for your reply! Do you know of other papers that can do glove recognition? I haven't found a suitable one yet. I am very much looking forward to your reply!

**Comment by SeanChenxy** [comment]
Sorry, I have not been aware of any method in this task.
