### ISSUE TITLE
what does xx_K.npy data indicate?

### ISSUE THREAD

**Issue by yanhn** [SeanChenxy/HandMesh#7]
Great thanks for your opensource. Very impressive work.
I tried the demo according to your instructions. And I am a little confused about the xx_K.npy files. I guess these files contains the camera info, but where can I get the corresponding info for my custom data? Could you please help me out, thanks.

**Comment by SeanChenxy** [comment]
Hi, yanhn. K is the intrinsic camera parameters. If you do not have it, you would like to assume a focal length. For example, you can use K=[[500, 0, 112], [0, 500, 112], [0, 0, 1]] for a 224*224 input. Note that root recovery is related to K. Although the mesh can be aligned to the image, the solved root coordinates could not accurate given an estimated K.

**Comment by yanhn** [comment]
Thanks for you reply. I used the default value as you suggested and good the acceptable result. Thank you.
