### ISSUE TITLE
F-score?

### ISSUE THREAD

**Issue by jackyyang9** [SeanChenxy/HandMesh#70]
Hello sir, I have some questions about the F-score.
Is not hand reconstruction a regression task?
Then why you used the F-Score in your paper (mobrecon) ?  
How exactly the computation way of the F-score?
What is the difference between it and accuracy in this task?

**Comment by SeanChenxy** [comment]
Hi, sorry for late reply. Please refer to https://competitions.codalab.org/competitions/21238#learn_the_details-evaluation for the explaination of F-score

**Comment by jackyyang9** [comment]
Thank you, sir. Cause the COVID-19 problem, I saw your reply just now. I totally understand the F-score in hand reconstruction. Thanks again.
