### ISSUE TITLE
How to get mesh GT file freihand_train_mesh.zip?

### ISSUE THREAD

**Issue by YingjieYin** [SeanChenxy/HandMesh#71]
I cann't find the freihand_train_mesh.zip in the official website of FreiHAND.  Do  the freihand_train_mesh.zip need to be generated by myself?

**Comment by clashroyaleisgood** [comment]
the zip file is provided by the author
https://github.com/SeanChenxy/HandMesh#install
> - Download the files you need from [Google drive](https://drive.google.com/drive/folders/1MIE0Jo01blG6RWo2trQbXlQ92tMOaLx_?usp=sharing) or [Baidu cloud](https://pan.baidu.com/s/12X1qsuxO2j8jGl6QWJdV6A?pwd=rc4x).

**Comment by YingjieYin** [comment]
> ok, thank you very much!
