### ISSUE TITLE
vert_gt为什么需要 /0.2的操作

### ISSUE THREAD

**Issue by yfynb1111** [SeanChenxy/HandMesh#72]
hi，作者您好：
  这是frehand.py最后gt处理，为什么要将mesh和3D骨架放大5倍呢，不太理解
    # postprocess root and joint_cam
    root = joint_cam[0].clone()
    joint_cam -= root
    vert -= root
    joint_cam /= 0.2

**Comment by SeanChenxy** [comment]
你好，这个操作并不太关键。普通人手的长度大概是0.2m，放大以后，数据就在 [-1, 1] 之间。
