### ISSUE TITLE
Question about .npz in cmr/images 

### ISSUE THREAD

**Issue by LiXm1002** [SeanChenxy/HandMesh#73]
Hi,
Thanks for sharing the code, but I'm confuse about the .npz in 'cmr/images'.
First, I run ./cmr/scripts/demo_mobrecon.sh and output successfully. Then I want to test my own data, I found `K = np.load(image_path.replace('_img.jpg', '_K.npy'))` in runner.py. 
But my data just images  in  '.jpg' format, how to get the corresponding .npy file?

I hope someone will answer my question, thanks in advance.

**Comment by SeanChenxy** [comment]
Hi, please see https://github.com/SeanChenxy/HandMesh/issues/7 to solve your issue.
