### ISSUE TITLE
about the convert between camera-space coordinate and root-relative coordinate

### ISSUE THREAD

**Issue by lvZic** [SeanChenxy/HandMesh#74]
https://github.com/SeanChenxy/HandMesh/blob/47e860cc046e4d36aad244fb8291e4ccf59a32a9/mobrecon/tools/registration.py#L20
我的理解是，如上函数估计出输入mesh中root点的3D坐标，实现了将root-relative coordinate转换为camera-space coordinate.

但我在实验中发现，基于不同的root点的root-relative coordinate，registration返回的camera-space coordinate是不一样的，比如以wrist作为root的mesh坐标和以mcp作为root的相同mesh坐标，registration得到的vertex+t（也即相机坐标系下的坐标）结果不一样，差异不小。
所以我想知道registration函数估计到的的t，置信度/精度有多大？

**Comment by SeanChenxy** [comment]
Hi, 使用mcp作为root时，确保mcp的位置为[0,0,0]。置信度/精度与2D pose、3D pose、silhouette的准确性有关，无法给出一个general的估计，可以根据优化过程的loss来判断置信度/精度。

**Comment by lvZic** [comment]
> Hi, 使用mcp作为root时，确保mcp的位置为[0,0,0]。置信度/精度与2D pose、3D pose、silhouette的准确性有关，无法给出一个general的估计，可以根据优化过程的loss来判断置信度/精度。

是的 作为root点的关节坐标是（0，0，0）。但是我实验中也确实发现不同关节点作为root的registration结果不同，所以可能是我的回归结果误差太大？
