### ISSUE TITLE
Can you upload the best pretrained model?

### ISSUE THREAD

**Issue by jackyyang9** [SeanChenxy/HandMesh#78]
Hello sir,
I noticed that the model you have uploaded on github is not the model with the best performance in Table 5 of your paper.
can you upload it?
In fact, I am in an emergency to compare your method with mine.
And this comparision will be done on FreHand dataset, and I will compute other metrics which is not usual (not PJ or  PV).
I would be much grateful if you can upload.

Thank you.

**Comment by SeanChenxy** [comment]
I apologize for being unable to upload anything else due to changes in my employment. ResNet50 model can be re-implemented referring to https://github.com/SeanChenxy/HandMesh/issues/65

**Comment by jackyyang9** [comment]
Okay， thanks for your anyway : ) .
