### ISSUE TITLE
Some questions about the results of 3D PCK on pose (RHD)

### ISSUE THREAD

**Issue by sean-001** [SeanChenxy/HandMesh#79]
Hi , it is a very great work, and  I feel a bit puzzled about the results on RHD.
RHD dataset doesn't contain the mesh data, so how is MobRecon trained on RHD ?

**Comment by SeanChenxy** [comment]
Hi, MobRecon produces a hand mesh that can also generate hand poses based on MANO's regressor. Then, RHD GT can be used for supervision.
