### ISSUE TITLE
How about the practical effect in real time video?

### ISSUE THREAD

**Issue by Guocode** [SeanChenxy/HandMesh#8]
Can you show your method on a real time video, changing the distance of Z axis for intuitively visualizing the jitter.

**Comment by SeanChenxy** [comment]
Hi, Guocode. I have tested the jitter with a video as follows. 


https://user-images.githubusercontent.com/23030658/125745590-dd8a3c8b-d762-46d7-b451-0b3572b76ffa.mp4


Then, I calculate the acceleration as follows (The x-axis is frame number while the y-axis is acceleration)
![image](https://user-images.githubusercontent.com/23030658/125741789-71d507da-5494-4250-ad21-e38bbd67e8e4.png)
The average accelerations are shown below.
```
mean acceleration (mm/s^2, pixel/s^2)
verts_x: 0.657   verts_y: 1.31   verts_z: 1.537   verts_norm: 2.42
xyz_x: 0.709   xyz_y: 1.393   xyz_z: 1.626   xyz_norm: 2.573
root_x: 0.787   root_y: 1.219   root_z: 7.697   root_norm: 8.072
uv_x: 1.274   uv_y: 1.814   uv_norm: 2.0
```

**Comment by Guocode** [comment]
@SeanChenxy Sorry, I failed to access the video, please check it.

**Comment by SeanChenxy** [comment]
> @SeanChenxy Sorry, I failed to access the video, please check it.

I have updated it.

**Comment by Guocode** [comment]
> > @SeanChenxy Sorry, I failed to access the video, please check it.
> 
> I have updated it.

Seems to need further optimization ^_^

**Comment by SeanChenxy** [comment]
Right. We do not use any strategy for temporal smoothness.
