### ISSUE TITLE
About the trained by only freihand pth

### ISSUE THREAD

**Issue by Jihyeon-2** [SeanChenxy/HandMesh#81]
Hi, Thank you for your nice work!

I just wanna ask do you have the pth file trained by only freihand dataset? (except the synthetic additional dataset)

If you have, can you share with us?

Thank you :)

**Comment by SeanChenxy** [comment]
Hi, this is easy to re-train by setting `DATASET: FreiHAND`
https://github.com/SeanChenxy/HandMesh/blob/dbdca0d4fba75d7b010762edd4499b8102e06071/mobrecon/configs/mobrecon_ds.yml#L17

**Comment by Jihyeon-2** [comment]
Okay :)
