### ISSUE TITLE
About the 3D PCK on mesh?

### ISSUE THREAD

**Issue by lpx153623** [SeanChenxy/HandMesh#82]
Can you send the script of draw 3D PCK on mesh? I need some help, Please! My mailbox is 2265103334@qq.com

**Comment by SeanChenxy** [comment]
You could need the following codes.
https://github.com/SeanChenxy/Hand3DResearch/blob/main/benchmarks/freihand/freihand_plots.py

**Comment by lpx153623** [comment]
Thank you very much!
