### ISSUE TITLE
SpiralConv Code Details

### ISSUE THREAD

**Issue by Jackson-coder** [SeanChenxy/HandMesh#83]
Dear Author, In the generate_spiral_seq.py file, I wonder why add "after_last_ring" to the selection process of the next ring of vertices?
![image](https://github.com/SeanChenxy/HandMesh/assets/56574281/df08ae4c-3200-4fd5-95ce-482b876dcb90)

Is there any negative effect if I change the code to the following?
![image](https://github.com/SeanChenxy/HandMesh/assets/56574281/fb5dc3db-aacc-442b-84f6-320669409de3)

**Comment by Jackson-coder** [comment]
?

**Comment by SeanChenxy** [comment]
Hi, sorry for late reply. You can raise an issue on [Spiralconv++](https://github.com/sw-gong/spiralnet_plus/blob/master/utils/generate_spiral_seq.py#L6) for a more accurate explanation.
