### ISSUE TITLE
Question about released densestack.pth

### ISSUE THREAD

**Issue by JoyboyWang** [SeanChenxy/HandMesh#84]
Hi, I saw from your paper that you have tried different backbones(GhostStack, DenseStack, ResNet, etc) trained on ImageNet and/or your complement data. 

I wanna know which dataset(ImageNet or complement data or both) did you use in training for your released "densestack.pth" ? Thanks in advance!

**Comment by SeanChenxy** [comment]
Hi, densestack.pth is pretrained with the complement data.
