### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by zy123456123** [SeanChenxy/HandMesh#87]
Hello, this requirement has not been passed. Will we be allowed to participate in this competition, and are there any other evaluation methods.
![图片](https://github.com/SeanChenxy/HandMesh/assets/76393070/0ef3e877-94cc-4bc4-b8c6-74e9fff63f59)

**Comment by SeanChenxy** [comment]
Hi, FreiHAND do not release th ground truth, and uploading results to the official server is necessary. There might be a delay of several days before they process your request.

**Comment by lyhsieh** [comment]
> Hello, this requirement has not been passed. Will we be allowed to participate in this competition, and are there any other evaluation methods. ![图片](https://private-user-images.githubusercontent.com/76393070/258584121-0ef3e877-94cc-4bc4-b8c6-74e9fff63f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjM0ODUsIm5iZiI6MTcxNjIyMzE4NSwicGF0aCI6Ii83NjM5MzA3MC8yNTg1ODQxMjEtMGVmM2U4NzctOTRjYy00YmM0LWI4YzYtNzRlOWZmZjYzZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE2Mzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YzIzNTYxODE3ODRkZDgyOGJjMDFkYTAxODVlN2Y1OWU2MDhkNzMyNjlhN2ZjYTEzYjcyNTY4NTMxNGIwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.azUB7VSbW7lYzbr_Uf5NqMtG0FI03FP9XA5Q_3Y-qqw)

@zy123456123 Is the competition available for upload now?
