### ISSUE TITLE
hand-obj interact

### ISSUE THREAD

**Issue by xiaoyudanaa** [SeanChenxy/HandMesh#90]
I'm honored to read this paper and I have a question: if I want to interact with a virtual 3D object using this method, how should I do?
I'd appreciate any code hints or specific pointers you could give. Thanks a million!

Looking forward to your reply.

**Comment by SeanChenxy** [comment]
Hi, if the virtual 3D object is depicted as a mesh, this code repository can help you accomplish your goal. The remaining task involves calculating the $SE(3)$ transformation for the virtual object based on the predicted hand mesh.

**Comment by xiaoyudanaa** [comment]
非常感谢您的回复，我可以加您的联系方式嘛，有些问题想请教您一下。我的微信号是：Weafree。谢谢您
