### ISSUE TITLE
Test my own dataset using demo_ The effect of cmr. sh is poor. And using demo_ Mobrecon.sh will have a better effect.

### ISSUE THREAD

**Issue by Sweetest316** [SeanChenxy/HandMesh#91]
Hello, thanks for share !
I encountered a strange problem:
I use demo_ The cmr. sh test on my own dataset showed very poor performance, as shown in Figure 1. And for using demo_ Mobrecon.sh will achieve better results, as shown in Figure 2.
Why is this? I hope you can answer my confusion.
Thank you first.

Figure 1：
![image](https://github.com/SeanChenxy/HandMesh/assets/87267028/25e15abf-36c4-41b2-8445-f4106f4709ff)

Figure 2：
![image](https://github.com/SeanChenxy/HandMesh/assets/87267028/e474b442-e382-4c1a-b022-976a20c6e44f)

**Comment by SeanChenxy** [comment]
Hi, our models support right hand, so you should filp images first.

**Comment by Sweetest316** [comment]
Thank you for your prompt reply.
But I still encountered the same problem：
![image](https://github.com/SeanChenxy/HandMesh/assets/87267028/240578b2-f353-4bd9-894e-f555391a3cc6)

At the same time, there is a strange phenomenon. I also predicted the demo image you provided, as follows, but the effect is surprisingly good. I think there is something wrong with my image itself?
![image](https://github.com/SeanChenxy/HandMesh/assets/87267028/e7b6d4c2-5ea9-4712-97d8-5f480c6f8347)

I uniformly set the K value to [[500, 0, 112], [0, 500, 112], [0, 0, 1]]

**Comment by jiabao-zhang** [comment]
By the way, although using demo_cmr.sh may not work well, I used demo_mobrecon.sh to achieve much better results, to the extent that testing the left hand also yielded relatively good results.

> Hello, thanks for share ! I encountered a strange problem: I use demo_ The cmr. sh test on my own dataset showed very poor performance, as shown in Figure 1. And for using demo_ Mobrecon.sh will achieve better results, as shown in Figure 2. Why is this? I hope you can answer my confusion. Thank you first.
> 
> Figure 1： ![image](https://user-images.githubusercontent.com/87267028/275738415-25e15abf-36c4-41b2-8445-f4106f4709ff.png)
> 
> Figure 2： ![image](https://user-images.githubusercontent.com/87267028/275737951-e474b442-e382-4c1a-b022-976a20c6e44f.png)

**Comment by Sweetest316** [comment]
By the way, although using demo_cmr.sh may not work well, I used demo_mobrecon.sh to achieve much better results, to the extent that testing the left hand also yielded relatively good results.

> Thank you for your prompt reply. But I still encountered the same problem： ![image](https://user-images.githubusercontent.com/87267028/275755922-240578b2-f353-4bd9-894e-f555391a3cc6.png)
> 
> At the same time, there is a strange phenomenon. I also predicted the demo image you provided, as follows, but the effect is surprisingly good. I think there is something wrong with my image itself? ![image](https://user-images.githubusercontent.com/87267028/275756806-e7b6d4c2-5ea9-4712-97d8-5f480c6f8347.png)
> 
> I uniformly set the K value to [[500, 0, 112], [0, 500, 112], [0, 0, 1]]

**Comment by SeanChenxy** [comment]
Hi, based on the information provided above, I am unable to identify the error. Note that MobRecon does not offer support for left-hand reconstruction. And, it exhibits better performance due to its extensive training data.
