### ISSUE TITLE
Test cmr_sg with freihand's checkpoint generates errors

### ISSUE THREAD

**Issue by JCheng314** [SeanChenxy/HandMesh#92]
I'm using cmr_sg with cmr_sg_res18_freihand.pt parameters, and applying that on my data creates some errors on images that seem ok. Could you please share some insights on what's going wrong here?
<img width="1124" alt="截屏2023-11-01 上午8 41 29" src="https://github.com/SeanChenxy/HandMesh/assets/124293491/08154d5c-e2ec-497f-a28f-2eb92d92e6f0">
<img width="1123" alt="截屏2023-11-01 上午8 41 48" src="https://github.com/SeanChenxy/HandMesh/assets/124293491/ca9b0bbc-b50d-4355-81f3-9972202bc81f">
By the way, similar issues happen to the evaluation set of Freihand too:
<img width="1121" alt="截屏2023-11-01 上午9 14 05" src="https://github.com/SeanChenxy/HandMesh/assets/124293491/f252c6d6-0745-462d-961c-957ea738ed7a">

**Comment by SeanChenxy** [comment]
Hi, please try the MobRecon (SpiralConv) model. Additionally, make sure to crop the image using the hand bounding box (1.3-time expansion).

**Comment by JCheng314** [comment]
Hi Sean,
Thanks a lot for the reply. Do you mind expanding upon what is the hand bounding box?
